[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
mio = { version = "1.0.4", features = ["os-poll", "net"] }
